# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 2c4b343d42f5d605b22b146b933b562eefc851069268a0ab3de0197800d31d59c03623061f7c600f22b6dfcb0782da0584ebf466ef238be1aca7f991ccd923b2

test:
  secret_key_base: 9c2f36d879544cdbcf56ee6c09366f6ad7992a9c706b3293dab79d7a574c6fba20764756c352ddb08b1537ae86a585150ee1060bd01e21fe29103f3ddd4f2e4d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
